### ISSUE TITLE
--config unclear / not implemented?

### ISSUE THREAD

**Issue by ruapho** [aquilax/hranoprovod-cli#53]
Hi,

the help states:
`--config FILE, -c FILE     Configuration file FILE (default: "/home/user/.hranoprovod/config") [$HR_CONFIG]`

I cannot find anything about the file format in your documentation and my short analysis of the code (i am no Go developer) leaves me without a trace.

Obviously the environment parameters are working well. Great software :+1:

**Comment by aquilax** [comment]
Thank you for pointing this out @ruapho Will add a short page about it.
